In [2]:
import tensorflow as tf 

In [3]:
class ScaledDotProductAttention(tf.keras.layers.Layer):
    def __init__(self):
        super(ScaledDotProductAttention  , self).__init__()
    
    def call(self , query , key , value , mask = None):
        matmul_qk = tf.matmul(query , key , transpose_b= True)
        dk  = tf.cast(tf.shape(key)[-1] , dtype = tf.float32)
        scaled_attendtion_logits = matmul_qk / tf.sqrt(dk)
        if mask is not None:
            scaled_attendtion_logits += (mask * -1e9)
        attention_weights = tf.nn.softmax(scaled_attendtion_logits)
        context_vector = tf.matmul(attention_weights , value)
        
        return context_vector , attention_weights 
    
    

In [9]:
# Test the attention 

query = tf.random.normal([1,60 , 512]) # [batch_size , sequence_length , hidden dims]
key = tf.random.normal([1, 60, 512])
value = tf.random.normal([1, 60 , 512])

attention_layer = ScaledDotProductAttention()
context_vector  , attention_weights = attention_layer(query , key ,value)

In [10]:
print("attention_weights shape : ",attention_weights.shape)
print("context_vector shape : ",context_vector.shape)

attention_weights shape :  (1, 60, 60)
context_vector shape :  (1, 60, 512)


In [11]:
context_vector , attention_weights

(<tf.Tensor: shape=(1, 60, 512), dtype=float32, numpy=
 array([[[ 0.17700657,  0.181385  , -0.20478751, ...,  0.09377327,
           0.06309219,  0.06153682],
         [ 0.03401825,  0.12424516, -0.09543878, ...,  0.3135886 ,
           0.11113255, -0.11701623],
         [ 0.04679409,  0.0247407 ,  0.26106104, ...,  0.23319082,
           0.14586933, -0.08070141],
         ...,
         [ 0.37619588, -0.1041597 ,  0.22569837, ...,  0.30400464,
          -0.12813361,  0.25159466],
         [ 0.15836282,  0.12380538, -0.18803303, ...,  0.03463506,
           0.32412484,  0.01808381],
         [ 0.15389511,  0.19485563,  0.0048784 , ...,  0.12644738,
           0.20467182, -0.07748351]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 60, 60), dtype=float32, numpy=
 array([[[0.02331792, 0.0091478 , 0.00264895, ..., 0.00545185,
          0.00654283, 0.00580621],
         [0.00313364, 0.03895336, 0.00517009, ..., 0.00870177,
          0.01769357, 0.0627395 ],
         [0.01095345, 0.00731473, 0.00